export const ADD_INGREDIENT_INSIDE_CONSTRUCTOR = 'ADD_INGREDIENT_INSIDE_CONSTRUCTOR';
export const REMOVE_INGREDIENT_INSIDE_CONSTRUCTOR = 'REMOVE_INGREDIENT_INSIDE_CONSTRUCTOR';


export const POST_EMAIL_FORGOT_PAGE_SUCCESS = 'POST_EMAIL_FORGOT_PAGE_SUCCESS';
export const POST_EMAIL_FORGOT_PAGE_FAILED = 'POST_EMAIL_FORGOT_PAGE_FAILED';
